language: ruby
cache: bundler
script: bundle exec rspec
sudo: false

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile

rvm:
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0

matrix:
  exclude:
  - rvm: 2.5.8
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.6.6
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.7.2
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/rails_5.0.gemfile

    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.6.6
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.7.2
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/rails_5.1.gemfile

  - rvm: 2.6.6
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 2.7.2
    gemfile: gemfiles/rails_5.2.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/rails_5.2.gemfile

    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.2.8
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 2.4.10
    gemfile: gemfiles/rails_6.0.gemfile
  - rvm: 3.0.0
    gemfile: gemfiles/rails_6.0.gemfile

  - rvm: 2.2.8
    gemfile: gemfiles/rails_6.1.gemfile
  - rvm: 2.3.8
    gemfile: gemfiles/rails_6.1.gemfile
  - rvm: 2.4.10
    gemfile: gemfiles/rails_6.1.gemfile
